import '@/shared/css/global.css'
import type { Metadata } from 'next'
import { Bebas_Neue } from 'next/font/google'
import { LenisProvider } from '@/shared/components'

const bebasNeue = Bebas_Neue({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by Miladev',
  icons: { icon: '/icons/favicon.svg' },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={bebasNeue.className}
      >
        <LenisProvider>{children}</LenisProvider>
      </body>
    </html>
  )
}
